<?php 

class Geography {
	static $STATES = array(
		'US'=>array(
			'AL'=>"Alabama",  
			'AK'=>"Alaska",  
			'AZ'=>"Arizona",  
			'AR'=>"Arkansas",  
			'CA'=>"California",  
			'CO'=>"Colorado",  
			'CT'=>"Connecticut",  
			'DE'=>"Delaware",  
			'DC'=>"District Of Columbia",  
			'FL'=>"Florida",  
			'GA'=>"Georgia",  
			'HI'=>"Hawaii",  
			'ID'=>"Idaho",  
			'IL'=>"Illinois",  
			'IN'=>"Indiana",  
			'IA'=>"Iowa",  
			'KS'=>"Kansas",  
			'KY'=>"Kentucky",  
			'LA'=>"Louisiana",  
			'ME'=>"Maine",  
			'MD'=>"Maryland",  
			'MA'=>"Massachusetts",  
			'MI'=>"Michigan",  
			'MN'=>"Minnesota",  
			'MS'=>"Mississippi",  
			'MO'=>"Missouri",  
			'MT'=>"Montana",
			'NE'=>"Nebraska",
			'NV'=>"Nevada",
			'NH'=>"New Hampshire",
			'NJ'=>"New Jersey",
			'NM'=>"New Mexico",
			'NY'=>"New York",
			'NC'=>"North Carolina",
			'ND'=>"North Dakota",
			'OH'=>"Ohio",  
			'OK'=>"Oklahoma",  
			'OR'=>"Oregon",  
			'PA'=>"Pennsylvania",  
			'RI'=>"Rhode Island",  
			'SC'=>"South Carolina",  
			'SD'=>"South Dakota",
			'TN'=>"Tennessee",  
			'TX'=>"Texas",  
			'UT'=>"Utah",  
			'VT'=>"Vermont",  
			'VA'=>"Virginia",  
			'WA'=>"Washington",  
			'WV'=>"West Virginia",  
			'WI'=>"Wisconsin",  
			'WY'=>"Wyoming"
		),
/**
	Canadian Provinces
*/
		'CA'=>array(
		    "BC"=>"British Columbia", 
		    "ON"=>"Ontario", 
		    "NL"=>"Newfoundland and Labrador", 
		    "NS"=>"Nova Scotia", 
		    "PE"=>"Prince Edward Island", 
		    "NB"=>"New Brunswick", 
		    "QC"=>"Quebec", 
		    "MB"=>"Manitoba", 
		    "SK"=>"Saskatchewan", 
		    "AB"=>"Alberta", 
		    "NT"=>"Northwest Territories", 
		    "NU"=>"Nunavut",
		    "YT"=>"Yukon Territory"
		),
/**
	Mexican States
*/
		'MX'=>array(
			"AG"=>"Aguascalientes",
			"BC"=>"Baja California Norte",
			"BS"=>"Baja California Sur",
			"CH"=>"Chihuahua",
			"CL"=>"Colima",
			"CM"=>"Campeche",
			"CO"=>"Coahuila",
			"CS"=>"Chiapas",
			"DF"=>"Distrito Federal",
			"DG"=>"Durango",
			"GR"=>"Guerrero",
			"GT"=>"Guanajuato",
			"HG"=>"Hidalgo",
			"JA"=>"Jalisco",
			"MI"=>"Michoacan",
			"MO"=>"Morelos",
			"NA"=>"Nayarit",
			"NL"=>"Nuevo Leon",
			"OA"=>"Oaxaca",
			"PU"=>"Puebla",
			"QR"=>"Quintana Roo",
			"QT"=>"Queretaro",
			"SI"=>"Sinaloa",
			"SL"=>"San Luis Potosi",
			"SO"=>"Sonora",
			"TB"=>"Tabasco",
			"TL"=>"Tlaxcala",
			"TM"=>"Tamaulipas",
			"VE"=>"Veracruz",
			"YU"=>"Yucatan",
			"ZA"=>"Zacatecas"
		),
		
/**
	German States
*/
		'DE'=>array(
			'BW'=>"Baden-Württemberg",
			'BY'=>"Bavaria (Bayern)",
			'BE'=>"Berlin",
			'BB'=>"Brandenburg BB",
			'HB'=>"Bremen (Freie Hansestadt Bremen)",
			'HH'=>"Hamburg",
			'HE'=>"Hesse (Hessen)",
			'MV'=>"Mecklenburg-Vorpommern",
			'NI'=>"Lower Saxony (Niedersachsen)",
			'NW'=>"North Rhine-Westphalia (Nordrhein-Westfalen)",
			'RP'=>"Rhineland-Palatinate (Rheinland-Pfalz)",
			'SL'=>"Saarland",
			'SN'=>"Saxony (Sachsen)",
			'ST'=>"Saxony-Anhalt (Sachsen-Anhalt)",
			'SH'=>"Schleswig-Holstein",
			'TH'=>"Thuringia (Thüringen)",
		),
/**
	Australian States
*/
		'AU'=>array(
		    "NSW"=>"New South Wales",
		    "VIC"=>"Victoria",
		    "QLD"=>"Queensland",
		    "TAS"=>"Tasmania",
		    "SA"=>"South Australia",
		    "WA"=>"Western Australia",
		    "NT"=>"Northern Territory",
		    "ACT"=>"Australian Capital Terrirory"
		),
/**
	United Kingdom Counties
*/
		'GB'=>array("Aberdeenshire"=>"Aberdeenshire","Angus/Forfarshire"=>"Angus/Forfarshire","Argyllshire"=>"Argyllshire",
			"Ayrshire"=>"Ayrshire","Banffshire"=>"Banffshire","Bedfordshire"=>"Bedfordshire","Berkshire"=>"Berkshire",
			"Berwickshire"=>"Berwickshire","Blaenau Gwent"=>"Blaenau Gwent","Bridgend"=>"Bridgend",
			"Buckinghamshire"=>"Buckinghamshire","Buteshire"=>"Buteshire","Caerphilly"=>"Caerphilly","Caithness"=>"Caithness",
			"Cambridgeshire"=>"Cambridgeshire","Cardiff"=>"Cardiff","Carmarthenshire"=>"Carmarthenshire",
			"Ceredigion"=>"Ceredigion","Cheshire"=>"Cheshire","Clackmannanshire"=>"Clackmannanshire",
			"Conwy"=>"Conwy","Cornwall"=>"Cornwall","Cromartyshire"=>"Cromartyshire","Cumberland"=>"Cumberland",
			"Denbighshire"=>"Denbighshire","Derbyshire"=>"Derbyshire","Devon"=>"Devon","Dorset"=>"Dorset",
			"Dumfriesshire"=>"Dumfriesshire","Dunbartonshire/Dumbartonshire"=>"Dunbartonshire/Dumbartonshire",
			"Durham"=>"Durham","East Lothian/Haddingtonshire"=>"East Lothian/Haddingtonshire","Essex"=>"Essex","Fife"=>"Fife",
			"Flintshire"=>"Flintshire","Gloucestershire"=>"Gloucestershire","Gwynedd"=>"Gwynedd","Hampshire"=>"Hampshire",
			"Herefordshire"=>"Herefordshire","Hertfordshire"=>"Hertfordshire","Huntingdonshire"=>"Huntingdonshire",
			"Inverness-shire"=>"Inverness-shire","Isle of Anglesey"=>"Isle of Anglesey","Kent"=>"Kent",
			"Kincardineshire"=>"Kincardineshire","Kinross-shire"=>"Kinross-shire","Kirkcudbrightshire"=>"Kirkcudbrightshire",
			"Lanarkshire"=>"Lanarkshire","Lancashire"=>"Lancashire","Leicestershire"=>"Leicestershire",
			"Lincolnshire"=>"Lincolnshire","Merthyr Tydfil"=>"Merthyr Tydfil","Middlesex"=>"Middlesex",
			"Midlothian/Edinburghshire"=>"Midlothian/Edinburghshire","Monmouthshire"=>"Monmouthshire",
			"Morayshire"=>"Morayshire","Nairnshire"=>"Nairnshire","Neath Port Talbot"=>"Neath Port Talbot",
			"Newport"=>"Newport","Norfolk"=>"Norfolk","Northamptonshire"=>"Northamptonshire",
			"Northumberland"=>"Northumberland","Nottinghamshire"=>"Nottinghamshire","Orkney"=>"Orkney",
			"Oxfordshire"=>"Oxfordshire","Peeblesshire"=>"Peeblesshire","Pembrokeshire"=>"Pembrokeshire",
			"Perthshire"=>"Perthshire","Powys"=>"Powys","Renfrewshire"=>"Renfrewshire",
			"Rhondda Cynon Taff"=>"Rhondda Cynon Taff","Ross-shire"=>"Ross-shire","Roxburghshire"=>"Roxburghshire",
			"Rutland"=>"Rutland","Selkirkshire"=>"Selkirkshire","Shetland"=>"Shetland","Shropshire"=>"Shropshire",
			"Somerset"=>"Somerset","Staffordshire"=>"Staffordshire","Stirlingshire"=>"Stirlingshire","Suffolk"=>"Suffolk",
			"Surrey"=>"Surrey","Sussex"=>"Sussex","Sutherland"=>"Sutherland","Swansea"=>"Swansea","Torfaen"=>"Torfaen",
			"Vale of Glamorgan"=>"Vale of Glamorgan","Warwickshire"=>"Warwickshire",
			"West Lothian/Linlithgowshire"=>"West Lothian/Linlithgowshire","Westmorland"=>"Westmorland",
			"Wigtownshire"=>"Wigtownshire","Wiltshire"=>"Wiltshire",
			"Worcestershire"=>"Worcestershire","Wrexham"=>"Wrexham","Yorkshire"=>"Yorkshire"
		),
/**
	Japanese Prefectures
*/
		'JP'=>array(
			"Aichi"		=>	"Aichi",
			"Akita"		=>	"Akita",
			"Aomori"	=>	"Aomori",
			"Chiba"		=>	"Chiba",
			"Ehime"		=>	"Ehime",
			"Fukui"		=>	"Fukui",
			"Fukuoka"	=>	"Fukuoka",
			"Fukushima"	=>	"Fukushima",
			"Gifu"   	=>	"Gifu",
			"Gumma"  	=>	"Gumma",
			"Hiroshima"	=>	"Hiroshima",
			"Hokkaido"	=>	"Hokkaido",
			"Hyogo"		=>	"Hyogo",
			"Ibaraki"	=>	"Ibaraki",
			"Ishikawa"	=>	"Ishikawa",
			"Iwate"		=>	"Iwate",
			"Kagawa"	=>	"Kagawa",
			"Kagoshima"	=>	"Kagoshima",
			"Kanagawa"	=>	"Kanagawa",
			"Kochi"		=>	"Kochi",
			"Kumamoto"	=>	"Kumamoto",
			"Kyoto"		=>	"Kyoto",
			"Mie"		=>	"Mie",
			"Miyagi"	=>	"Miyagi",
			"Miyazaki"	=>	"Miyazaki",
			"Nagano"	=>	"Nagano",
			"Nagasaki"	=>	"Nagasaki",
			"Nara"		=>	"Nara",
			"Niigata"	=>	"Niigata",
			"Oita"		=>	"Oita",
			"Okayama"	=>	"Okayama",
			"Okinawa"	=>	"Okinawa",
			"Osaka"		=>	"Osaka",
			"Saga"		=>	"Saga",
			"Saitama"	=>	"Saitama",
			"Shiga"		=>	"Shiga",
			"Shimane"	=>	"Shimane",
			"Shizuoka"	=>	"Shizuoka",
			"Tochigi"	=>	"Tochigi",
			"Tokushima"	=>	"Tokushima",
			"Tokyo"		=>	"Tokyo",
			"Tottori"	=>	"Tottori",
			"Toyama"	=>	"Toyama",
			"Wakayama"	=>	"Wakayama",
			"Yamagata"	=>	"Yamagata",
			"Yamaguchi"	=>	"Yamaguchi",
			"Yamanashi" => "Yamanashi"
		),
/**
	Provinces of China
*/
		'CN'=>array(
			'BJ'=>'Beijing',
			'TJ'=>'Tianjin',
			'HE'=>'Hebei',
			'SX'=>'Shanxi',
			'NM'=>'Inner Mongolia',
			'LN'=>'Liaoning',
			'JL'=>'Jilin',
			'HL'=>'Heilongjiang',
			'SH'=>'Shanghai',
			'JS'=>'Jiangsu',
			'ZJ'=>'Zhejiang',
			'AH'=>'Anhui',
			'FJ'=>'Fujian',
			'JX'=>'Jiangxi',
			'SD'=>'Shandong',
			'HA'=>'Henan',
			'HB'=>'Hubei',
			'HN'=>'Hunan',
			'GD'=>'Guangdong',
			'GX'=>'Guangxi Zhuang',
			'HI'=>'Hainan',
			'CQ'=>'Chongqing',
			'SC'=>'Sichuan',
			'GZ'=>'Guizhou',
			'YN'=>'Yunnan',
			'XZ'=>'Tibet (Xizang)',
			'SN'=>'Shaanxi',
			'GS'=>'Gansu',
			'QH'=>'Qinghai',
			'NX'=>'Ningxia Hui',
			'XJ'=>'Xinjiang Uyghur',
			'HK'=>'Hong Kong (Xianggang)',
			'MC'=>'Macau (Aomen)',
			'TW'=>'Taiwan'
		),
/**
	Indian States and Union Territories
*/
		'IN'=>array(
			'AP'=>'Andhra Pradesh',
			'AR'=>'Arunachal Pradesh',
			'AS'=>'Assam',
			'BR'=>'Bihar',
			'CG'=>'Chhattisgarh',
			'GA'=>'Goa',
			'GJ'=>'Gujarat',
			'HR'=>'Haryana',
			'HP'=>'Himachal Pradesh',
			'JK'=>'Jammu and Kashmir',
			'JH'=>'Jharkhand',
			'KA'=>'Karnataka',
			'KL'=>'Kerala',
			'MP'=>'Madhya Pradesh',
			'MH'=>'Maharashtra',
			'MN'=>'Manipur',
			'ML'=>'Meghalaya',
			'MZ'=>'Mizoram',
			'NL'=>'Nagaland',
			'OR'=>'Orissa',
			'PB'=>'Punjab',
			'RJ'=>'Rajasthan',
			'SK'=>'Sikkim',
			'TN'=>'Tamil Nadu',
			'TR'=>'Tripura',
			'UP'=>'Uttar Pradesh',
			'UK'=>'Uttarakhand',
			'WB'=>'West Bengal',
			'AN'=>'Andaman and Nicobar Islands',
			'CH'=>'Chandigarh',
			'DB'=>'Dadra and Nagar Haveli',
			'DD'=>'Daman and Diu',
			'LD'=>'Lakshadweep',
			'ND'=>'National Capital Territory',
			'PY'=>'Pondicherry'
		)
	);
	
	static $COUNTRIES = array(
	  "US" => "United States",
	  "GB" => "United Kingdom",
	  "AF" => "Afghanistan",
	  "AL" => "Albania",
	  "DZ" => "Algeria",
	  "AS" => "American Samoa",
	  "AD" => "Andorra",
	  "AO" => "Angola",
	  "AI" => "Anguilla",
	  "AQ" => "Antarctica",
	  "AG" => "Antigua And Barbuda",
	  "AR" => "Argentina",
	  "AM" => "Armenia",
	  "AW" => "Aruba",
	  "AU" => "Australia",
	  "AT" => "Austria",
	  "AZ" => "Azerbaijan",
	  "BS" => "Bahamas",
	  "BH" => "Bahrain",
	  "BD" => "Bangladesh",
	  "BB" => "Barbados",
	  "BY" => "Belarus",
	  "BE" => "Belgium",
	  "BZ" => "Belize",
	  "BJ" => "Benin",
	  "BM" => "Bermuda",
	  "BT" => "Bhutan",
	  "BO" => "Bolivia",
	  "BA" => "Bosnia And Herzegowina",
	  "BW" => "Botswana",
	  "BV" => "Bouvet Island",
	  "BR" => "Brazil",
	  "IO" => "British Indian Ocean Territory",
	  "BN" => "Brunei Darussalam",
	  "BG" => "Bulgaria",
	  "BF" => "Burkina Faso",
	  "BI" => "Burundi",
	  "KH" => "Cambodia",
	  "CM" => "Cameroon",
	  "CA" => "Canada",
	  "CV" => "Cape Verde",
	  "KY" => "Cayman Islands",
	  "CF" => "Central African Republic",
	  "TD" => "Chad",
	  "CL" => "Chile",
	  "CN" => "China",
	  "CX" => "Christmas Island",
	  "CC" => "Cocos (Keeling) Islands",
	  "CO" => "Colombia",
	  "KM" => "Comoros",
	  "CG" => "Congo",
	  "CD" => "Congo, The Democratic Republic Of The",
	  "CK" => "Cook Islands",
	  "CR" => "Costa Rica",
	  "CI" => "Cote D'Ivoire",
	  "HR" => "Croatia (Local Name: Hrvatska)",
	  "CU" => "Cuba",
	  "CY" => "Cyprus",
	  "CZ" => "Czech Republic",
	  "DK" => "Denmark",
	  "DJ" => "Djibouti",
	  "DM" => "Dominica",
	  "DO" => "Dominican Republic",
	  "TP" => "East Timor",
	  "EC" => "Ecuador",
	  "EG" => "Egypt",
	  "SV" => "El Salvador",
	  "GQ" => "Equatorial Guinea",
	  "ER" => "Eritrea",
	  "EE" => "Estonia",
	  "ET" => "Ethiopia",
	  "FK" => "Falkland Islands (Malvinas)",
	  "FO" => "Faroe Islands",
	  "FJ" => "Fiji",
	  "FI" => "Finland",
	  "FR" => "France",
	  "FX" => "France, Metropolitan",
	  "GF" => "French Guiana",
	  "PF" => "French Polynesia",
	  "TF" => "French Southern Territories",
	  "GA" => "Gabon",
	  "GM" => "Gambia",
	  "GE" => "Georgia",
	  "DE" => "Germany",
	  "GH" => "Ghana",
	  "GI" => "Gibraltar",
	  "GR" => "Greece",
	  "GL" => "Greenland",
	  "GD" => "Grenada",
	  "GP" => "Guadeloupe",
	  "GU" => "Guam",
	  "GT" => "Guatemala",
	  "GN" => "Guinea",
	  "GW" => "Guinea-Bissau",
	  "GY" => "Guyana",
	  "HT" => "Haiti",
	  "HM" => "Heard And Mc Donald Islands",
	  "VA" => "Holy See (Vatican City State)",
	  "HN" => "Honduras",
	  "HK" => "Hong Kong",
	  "HU" => "Hungary",
	  "IS" => "Iceland",
	  "IN" => "India",
	  "ID" => "Indonesia",
	  "IR" => "Iran (Islamic Republic Of)",
	  "IQ" => "Iraq",
	  "IE" => "Ireland",
	  "IL" => "Israel",
	  "IT" => "Italy",
	  "JM" => "Jamaica",
	  "JP" => "Japan",
	  "JO" => "Jordan",
	  "KZ" => "Kazakhstan",
	  "KE" => "Kenya",
	  "KI" => "Kiribati",
	  "KP" => "Korea, Democratic People's Republic Of",
	  "KR" => "Korea, Republic Of",
	  "KW" => "Kuwait",
	  "KG" => "Kyrgyzstan",
	  "LA" => "Lao People's Democratic Republic",
	  "LV" => "Latvia",
	  "LB" => "Lebanon",
	  "LS" => "Lesotho",
	  "LR" => "Liberia",
	  "LY" => "Libyan Arab Jamahiriya",
	  "LI" => "Liechtenstein",
	  "LT" => "Lithuania",
	  "LU" => "Luxembourg",
	  "MO" => "Macau",
	  "MK" => "Macedonia, Former Yugoslav Republic Of",
	  "MG" => "Madagascar",
	  "MW" => "Malawi",
	  "MY" => "Malaysia",
	  "MV" => "Maldives",
	  "ML" => "Mali",
	  "MT" => "Malta",
	  "MH" => "Marshall Islands",
	  "MQ" => "Martinique",
	  "MR" => "Mauritania",
	  "MU" => "Mauritius",
	  "YT" => "Mayotte",
	  "MX" => "Mexico",
	  "FM" => "Micronesia, Federated States Of",
	  "MD" => "Moldova, Republic Of",
	  "MC" => "Monaco",
	  "MN" => "Mongolia",
	  "MS" => "Montserrat",
	  "MA" => "Morocco",
	  "MZ" => "Mozambique",
	  "MM" => "Myanmar",
	  "NA" => "Namibia",
	  "NR" => "Nauru",
	  "NP" => "Nepal",
	  "NL" => "Netherlands",
	  "AN" => "Netherlands Antilles",
	  "NC" => "New Caledonia",
	  "NZ" => "New Zealand",
	  "NI" => "Nicaragua",
	  "NE" => "Niger",
	  "NG" => "Nigeria",
	  "NU" => "Niue",
	  "NF" => "Norfolk Island",
	  "MP" => "Northern Mariana Islands",
	  "NO" => "Norway",
	  "OM" => "Oman",
	  "PK" => "Pakistan",
	  "PW" => "Palau",
	  "PA" => "Panama",
	  "PG" => "Papua New Guinea",
	  "PY" => "Paraguay",
	  "PE" => "Peru",
	  "PH" => "Philippines",
	  "PN" => "Pitcairn",
	  "PL" => "Poland",
	  "PT" => "Portugal",
	  "PR" => "Puerto Rico",
	  "QA" => "Qatar",
	  "RE" => "Reunion",
	  "RO" => "Romania",
	  "RU" => "Russian Federation",
	  "RW" => "Rwanda",
	  "KN" => "Saint Kitts And Nevis",
	  "LC" => "Saint Lucia",
	  "VC" => "Saint Vincent And The Grenadines",
	  "WS" => "Samoa",
	  "SM" => "San Marino",
	  "ST" => "Sao Tome And Principe",
	  "SA" => "Saudi Arabia",
	  "SN" => "Senegal",
	  "SC" => "Seychelles",
	  "SL" => "Sierra Leone",
	  "SG" => "Singapore",
	  "SK" => "Slovakia (Slovak Republic)",
	  "SI" => "Slovenia",
	  "SB" => "Solomon Islands",
	  "SO" => "Somalia",
	  "ZA" => "South Africa",
	  "GS" => "South Georgia, South Sandwich Islands",
	  "ES" => "Spain",
	  "LK" => "Sri Lanka",
	  "SH" => "St. Helena",
	  "PM" => "St. Pierre And Miquelon",
	  "SD" => "Sudan",
	  "SR" => "Suriname",
	  "SJ" => "Svalbard And Jan Mayen Islands",
	  "SZ" => "Swaziland",
	  "SE" => "Sweden",
	  "CH" => "Switzerland",
	  "SY" => "Syrian Arab Republic",
	  "TW" => "Taiwan",
	  "TJ" => "Tajikistan",
	  "TZ" => "Tanzania, United Republic Of",
	  "TH" => "Thailand",
	  "TG" => "Togo",
	  "TK" => "Tokelau",
	  "TO" => "Tonga",
	  "TT" => "Trinidad And Tobago",
	  "TN" => "Tunisia",
	  "TR" => "Turkey",
	  "TM" => "Turkmenistan",
	  "TC" => "Turks And Caicos Islands",
	  "TV" => "Tuvalu",
	  "UG" => "Uganda",
	  "UA" => "Ukraine",
	  "AE" => "United Arab Emirates",
	  "UM" => "United States Minor Outlying Islands",
	  "UY" => "Uruguay",
	  "UZ" => "Uzbekistan",
	  "VU" => "Vanuatu",
	  "VE" => "Venezuela",
	  "VN" => "Viet Nam",
	  "VG" => "Virgin Islands (British)",
	  "VI" => "Virgin Islands (U.S.)",
	  "WF" => "Wallis And Futuna Islands",
	  "EH" => "Western Sahara",
	  "YE" => "Yemen",
	  "YU" => "Yugoslavia",
	  "ZM" => "Zambia",
	  "ZW" => "Zimbabwe"
	);
}
